# build status appears on https://github.com/haproxy/haproxy/actions

name: windows-latest

on: [push]

jobs:
  cygwin:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: install prerequisites
      run: choco install bash make libssl-devel cygwin-devel gcc-core libgcc1 binutils lua-devel libpcre-devel zlib-devel --source cygwin
    - name: fake step
      run: C:\\tools\\cygwin\\bin\\bash -lc 'pwd'
    - name: build
      run: C:\\tools\\cygwin\\bin\\bash -lc 'cd $OLDPWD && make TARGET=cygwin ERR=1 USE_ZLIB=1 USE_PCRE=1 USE_PCRE_JIT=1 USE_LUA=1 USE_OPENSSL=1 USE_THREAD=1 && ./haproxy -vv'

